name: .NET Core Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --output $GITHUB_WORKSPACE
    - name: Publish
      run: dotnet nuget push $GITHUB_WORKSPACE/*.nupkg -s https://nuget.pkg.github.com/nifix777/index.json -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
